log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

email:
  sender: "your.email@mail.com"
  password: "super_strong_password"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: email-subscription-svc
  service_port: 80
